#define CONFIG_MQTT_THERMOSTAT 1
#define CONFIG_MQTT_DEVICE_TYPE "device_type"
#define CONFIG_MQTT_CLIENT_ID "client_id"
#define CONFIG_MQTT_THERMOSTAT_RELAY_ID 0
#define CONFIG_MQTT_THERMOSTAT_ROOMS_SENSORS_NB 1
#define CONFIG_MQTT_THERMOSTAT_ROOM_0_SENSORS_TOPIC "some/fake/sensor/topic"

#define CONFIG_MQTT_THERMOSTAT_HEATING_OPTIMIZER 1

#define CONFIG_MQTT_THERMOSTATS_NB 4

/* #define CONFIG_MQTT_RELAYS_NB 1 */

#define CONFIG_MQTT_USERNAME "username"
#define CONFIG_MQTT_PASSWORD "pass"
#define CONFIG_MQTT_SERVER "mqtt.server"
#define CONFIG_MQTT_PORT "12345"



int esp_get_free_heap_size();

