#define CONFIG_MQTT_THERMOSTAT 1
#define CONFIG_DEVICE_TYPE "device_type"
#define CONFIG_CLIENT_ID "client_id"
#define CONFIG_MQTT_THERMOSTAT_RELAY_ID 0
#define CONFIG_MQTT_THERMOSTAT_ROOMS_SENSORS_NB 1
#define CONFIG_MQTT_THERMOSTAT_ROOM_0_SENSORS_TOPIC "some/fake/sensor/topic"
#define CONFIG_MQTT_THERMOSTATS_TICK_PERIOD 60
#define CONFIG_MQTT_THERMOSTAT_HEATING_OPTIMIZER 1
#define CONFIG_MQTT_THERMOSTAT_ENABLE_NOTIFICATIONS 1

#define CONFIG_MQTT_THERMOSTATS_NB 4
#define CONFIG_MQTT_THERMOSTATS_NB0_FRIENDLY_NAME "t0"
#define CONFIG_MQTT_THERMOSTATS_NB1_FRIENDLY_NAME "t1"
#define CONFIG_MQTT_THERMOSTATS_NB2_FRIENDLY_NAME "t2"
#define CONFIG_MQTT_THERMOSTATS_NB3_FRIENDLY_NAME "t3"

#define CONFIG_NORTH_INTERFACE_MQTT
#define CONFIG_MQTT_SCHEDULERS

/* #define CONFIG_MQTT_RELAYS_NB 1 */

#define CONFIG_MQTT_USERNAME "username"
#define CONFIG_MQTT_PASSWORD "pass"
#define CONFIG_MQTT_SERVER "mqtt.server"
#define CONFIG_MQTT_PORT "12345"



int esp_get_free_heap_size();

